// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bootshop.DataAccess.Data;

namespace bootshop.DataAccess.Migrations
{
    [DbContext(typeof(bootshopDbContext))]
    [Migration("20220404170151_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bootshop.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phones"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TVs"
                        });
                });

            modelBuilder.Entity("bootshop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 1,
                            Discount = 0.14999999999999999,
                            ImageURL = "https://productimages.hepsiburada.net/s/41/200-200/10698988879922.jpg",
                            Name = "IPhone 12",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 1,
                            Discount = 0.14999999999999999,
                            ImageURL = "https://productimages.hepsiburada.net/s/41/200-200/10698988879922.jpg",
                            Name = "IPhone 13",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 1,
                            Discount = 0.14999999999999999,
                            ImageURL = "https://productimages.hepsiburada.net/s/41/200-200/10698988879922.jpg",
                            Name = "IPhone 14",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 1,
                            Discount = 0.14999999999999999,
                            ImageURL = "https://productimages.hepsiburada.net/s/41/200-200/10698988879922.jpg",
                            Name = "IPhone 16",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 2,
                            Discount = 0.14999999999999999,
                            ImageURL = "https://productimages.hepsiburada.net/s/139/200-200/110000091548721.jpg",
                            Name = "Lenovo Y700",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryID = 2,
                            Discount = 0.14999999999999999,
                            ImageURL = "https://productimages.hepsiburada.net/s/139/200-200/110000091548721.jpg",
                            Name = "Asus Y720",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryID = 2,
                            Discount = 0.14999999999999999,
                            ImageURL = "https://productimages.hepsiburada.net/s/139/200-200/110000091548721.jpg",
                            Name = "Dell Y750",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryID = 2,
                            Discount = 0.14999999999999999,
                            ImageURL = "https://productimages.hepsiburada.net/s/139/200-200/110000091548721.jpg",
                            Name = "Sony Vaio",
                            Price = 25000.0
                        });
                });

            modelBuilder.Entity("bootshop.Entities.Product", b =>
                {
                    b.HasOne("bootshop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("bootshop.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
